language: ruby
rvm:
  - 2.6

sudo: require

services:
  - docker

install:
  - gem install dip
  - gem install danger

before_script:
  - unset BUNDLE_GEMFILE
  - dip provision

script:
  - danger
  - dip rubocop
  - dip rspec
